name: socket_demo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  dio: ^5.1.1
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  socket_io_client: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
